Fix #5 - Error: Cannot find module 'reactify'
* react-tools and reactify have been deprecated in
favor of babel.

* See https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

* `reactify` has been replaced by the `babelify` browserify transform.